### ISSUE TITLE
Tracker for Differentiation Interface integration

### ISSUE THREAD

**Issue by oscardssmith** [SciML/OrdinaryDiffEq.jl#2484]
* [ ] Support autodiff=ADTypes
* [ ] Deprecate autodiff=true
* [ ] Fix/remove? FunctionWrappers
* [ ] coloring/sparsity?
* [ ] https://github.com/SciML/OrdinaryDiffEq.jl/pull/2482
